project_id = "xdnliyuogkoxckbesktx"

[functions.admin-create-user]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = true

[functions.sla-automations]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.create-payment-link]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false
